### ISSUE TITLE
Releasing object detection

### ISSUE THREAD

**Issue by MaryAhn** [hunto/DIST_KD#11]
Hi, first of all, thank you for your good research.
I would like to utilize your object detection implementation for my project, so would you like to release or send the object detection code of DIST?

Thanks in advance.
Mary.

**Comment by hunto** [comment]
Hi @MaryAhn ,

As discribed in [README#Object Detection](https://github.com/hunto/DIST_KD#coco-detection), we have uploaded the training code and configs in another repo. You can easily reimplement our results or extend it following the instructions in README.

Thanks.

**Comment by MaryAhn** [comment]
Thanks a lot!
ᐧ

2023년 9월 6일 (수) 오후 6:22, Tao Huang ***@***.***>님이 작성:
