### ISSUE TITLE
ModuleNotFoundError: No module named 'dataset'

### ISSUE THREAD

**Issue by zifuwanggg** [hunto/DIST_KD#3]
When running `train_kd.py`:

```
Traceback (most recent call last):
  File "train_kd.py", line 28, in <module>
    from dataset.datasets import CSTrainValSet
```

**Comment by hunto** [comment]
Hi @zifuwanggg ,

Sorry, we forgot to add the dataset directory in the code, it has now been added to the latest code (https://github.com/hunto/DIST_KD/commit/e500a39290b4df82b32e8aed5863cd9501e04dab).

You can pull the update and this error should be fixed now :)

**Comment by zifuwanggg** [comment]
Thanks for the quick reply! Now it runs smoothly.
