### ISSUE TITLE
关于MaskRCNN- FasterRCNN实验设置

### ISSUE THREAD

**Issue by luckinPP** [hunto/DIST_KD#9]
您好！发现在MaskRCNN- FasterRCNN的实验上，config做了较多的改动，尤其是teacher设置了三个bbox head，且设置参数都与mmdet的默认参数不同，请问这样设置的原因是什么呢？以及这个KDShared2FCBBoxHead 在包内找不到，其他注释的部分该如何使用呢？ 谢谢！

**Comment by hunto** [comment]
Hi @flyme-psp ,

我们的teacher模型follow的是之前检测KD paper的setting，用的是Cascade Mask R-CNN [(config)](https://github.com/open-mmlab/mmdetection/blob/main/configs/cascade_rcnn/cascade-mask-rcnn_x101-64x4d_fpn_20e_coco.py)，而不是Mask R-CNN，因此teacher会有Cascade提出的三个bbox head。

`KDShared2FCBBoxHead`这个类在https://github.com/hunto/MasKD/blob/main/mmrazor/mmrazor/models/utils/kd_bbox_head.py ，如果你是用的这里的mmrazor代码跑训练，这个head会被自动注册进mmdet中，训练应该是正常的。

其他注释的部分该如何使用：你说的是我们的config里将cascade后面两个head给注释掉了？因为faster r-cnn只有一层回归和分类head，而cascade是3层head的级联，在kd中我们只需要使用第一层的输出做蒸馏，因此后面两层不需要算了，注释掉可以节省这部分计算量。如果你想使用注释掉的这些层的输出，把注释取消掉，再修改蒸馏的位置就好了。
